services:
  - type: web
    name: my-express-store
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: development
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false